## F2019 DL & NN Class
## Austin Placinto
I have neither given nor received any unauthorized aid in completing this work, nor have I presented someone else's work as my own.

In [1]:
import keras
keras.__version__

from keras.datasets import imdb

(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000) 

# word_index is a dictionary mapping words to an integer index
word_index = imdb.get_word_index()

Using TensorFlow backend.


1646592/1641221 [==============================] - 0s 0us/step


In [0]:
import numpy as np

def vectorize_sequences(sequences, dimension=10000):
    # Create an all-zero matrix of shape (len(sequences), dimension)
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.  # set specific indices of results[i] to 1s
    return results

# Our vectorized training data
x_train = vectorize_sequences(train_data)
# Our vectorized test data
x_test = vectorize_sequences(test_data)

In [3]:
# Our vectorized labels
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')
y_test

array([0., 1., 1., ..., 0., 0., 0.], dtype=float32)

In [4]:
from keras import models
from keras import layers

model2 = models.Sequential()
model2.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model2.add(layers.Dense(16, activation='relu'))
model2.add(layers.Dense(1, activation='sigmoid'))

model2.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model2.fit(x_train, y_train, epochs=3, batch_size=512)






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/3
25000/25000 [==============================] - 3s 103us/step - loss: 0.4579 - acc: 0.8218
Epoch 2/3
25000/25000 [==============================] - 2s 74us/step - loss: 0.2630 - acc: 0.9100
Epoch 3/3
25000/25000 [==============================] - 2s 74us/step - loss: 0.2016 - acc: 0.9286


In [5]:
results2 = model2.evaluate(x_test, y_test)
print(model2.metrics_names)
results2

25000/25000 [==============================] - 2s 92us/step
['loss', 'acc']


[0.28077427472114563, 0.88808]

In [6]:
my_test_data_txt = [['i', 'love', 'it', 'very', 'good', 'movie'], 
    ['i', 'dislike', 'it', 'terrible', 'worst', 'ever'], 
    ['it', 'is', 'a', 'bad', 'and', 'boring', 'movie'], 
    ['fun', 'and', 'interesting', 'movie', 'i', 'enjoyed', 'it']]
my_test_labels = [1, 0, 0, 1]
y_my_test = np.asarray(my_test_labels).astype('float32')

my_test_data_rows = []
my_test_data = []

for sentence in my_test_data_txt:
  my_test_data_rows = []
  for word in sentence:
    my_test_data_rows.append(word_index[word]+3)
  my_test_data.append(my_test_data_rows)
            
x_my_test = vectorize_sequences(my_test_data) # convert into numpy array with indices equalling 1 or 0

print(my_test_data)
print(model2.predict(x_my_test))
print(model2.evaluate(x_my_test, y_my_test))
print(my_test_labels)

[[13, 119, 12, 55, 52, 20], [13, 3122, 12, 394, 249, 126], [12, 9, 6, 78, 5, 357, 20], [253, 5, 221, 20, 13, 510, 12]]
[[0.6376078 ]
 [0.30221972]
 [0.29150167]
 [0.6719881 ]]
4/4 [==============================] - 0s 229us/step
[0.3880012631416321, 1.0]
[1, 0, 0, 1]


Expected Output is like:

```
model2.predict(x_my_test)
array([[0.661295  ],
       [0.32133913],
       [0.3113112 ],
       [0.6984629 ]], dtype=float32)
```



---
## (HW6.2) Further experiments using Markdown Text Cells

1. We were using 2 hidden layers. <br>
(a) Try to use 1 hidden layer with 16 neurons and see how it affects validation and test accuracy. <br>
(b) Try to use 3 hidden layers (16, 16, 16) and see how it affects validation and test accuracy.

2. Try to use 2 layers with more (32, 32) hidden units
3. Try to use the `mse` loss function instead of `binary_crossentropy` with (16, 16, 1) architecture.
4. Try to use the `tanh` activation (an activation that was popular in the early days of neural networks) <br>
instead of `relu` with (16, 16, 1) architecture.

These experiments will help convince you that the architecture choices we have made are all fairly reasonable, <br>although they can still be improved.

Another objective of this HW6.2 is to practice documentation using Markdown in Python Jupyter Notebook.

## HW 6.2 #1.a)

In [7]:
from keras import models
from keras import layers

model621a = models.Sequential()
model621a.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model621a.add(layers.Dense(1, activation='sigmoid'))

model621a.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model621a.fit(x_train, y_train, epochs=3, batch_size=512)
print(model621a.predict(x_my_test))

Epoch 1/3
25000/25000 [==============================] - 2s 82us/step - loss: 0.4600 - acc: 0.8282
Epoch 2/3
25000/25000 [==============================] - 2s 74us/step - loss: 0.2868 - acc: 0.9056
Epoch 3/3
25000/25000 [==============================] - 2s 75us/step - loss: 0.2261 - acc: 0.9230
[[0.6495842 ]
 [0.32721886]
 [0.32183015]
 [0.6688528 ]]


## HW 6.2 #1.b)

In [8]:
from keras import models
from keras import layers

model621b = models.Sequential()
model621b.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model621b.add(layers.Dense(16, activation='relu'))
model621b.add(layers.Dense(16, activation='relu'))
model621b.add(layers.Dense(1, activation='sigmoid'))

model621b.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model621b.fit(x_train, y_train, epochs=3, batch_size=512)
print(model621b.predict(x_my_test))

Epoch 1/3
25000/25000 [==============================] - 2s 85us/step - loss: 0.4548 - acc: 0.8129
Epoch 2/3
25000/25000 [==============================] - 2s 75us/step - loss: 0.2489 - acc: 0.9104
Epoch 3/3
25000/25000 [==============================] - 2s 75us/step - loss: 0.1916 - acc: 0.9294
[[0.66696066]
 [0.30661502]
 [0.28654453]
 [0.6805932 ]]


## HW 6.2 #2

In [9]:
from keras import models
from keras import layers

model622 = models.Sequential()
model622.add(layers.Dense(32, activation='relu', input_shape=(10000,)))
model622.add(layers.Dense(32, activation='relu'))
model622.add(layers.Dense(1, activation='sigmoid'))

model622.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model622.fit(x_train, y_train, epochs=3, batch_size=512)
print(model622.predict(x_my_test))

Epoch 1/3
25000/25000 [==============================] - 2s 98us/step - loss: 0.4175 - acc: 0.8234
Epoch 2/3
25000/25000 [==============================] - 2s 89us/step - loss: 0.2387 - acc: 0.9103
Epoch 3/3
25000/25000 [==============================] - 2s 89us/step - loss: 0.1839 - acc: 0.9328
[[0.65119356]
 [0.26084006]
 [0.25527322]
 [0.6956111 ]]


## HW 6.2 #3

In [10]:
from keras import models
from keras import layers

model623 = models.Sequential()
model623.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model623.add(layers.Dense(16, activation='relu'))
model623.add(layers.Dense(1, activation='sigmoid'))

model623.compile(optimizer='rmsprop',
              loss='mse',
              metrics=['accuracy'])

model623.fit(x_train, y_train, epochs=3, batch_size=512)
print(model623.predict(x_my_test))

Epoch 1/3
25000/25000 [==============================] - 2s 90us/step - loss: 0.1521 - acc: 0.8190
Epoch 2/3
25000/25000 [==============================] - 2s 76us/step - loss: 0.0799 - acc: 0.9088
Epoch 3/3
25000/25000 [==============================] - 2s 76us/step - loss: 0.0597 - acc: 0.9304
[[0.6358258 ]
 [0.37011698]
 [0.34967592]
 [0.6811948 ]]


## HW 6.2 #4

In [11]:
from keras import models
from keras import layers

model624 = models.Sequential()
model624.add(layers.Dense(16, activation='tanh', input_shape=(10000,)))
model624.add(layers.Dense(16, activation='tanh'))
model624.add(layers.Dense(1, activation='sigmoid'))

model624.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model624.fit(x_train, y_train, epochs=3, batch_size=512)
print(model624.predict(x_my_test))

Epoch 1/3
25000/25000 [==============================] - 2s 92us/step - loss: 0.4220 - acc: 0.8296
Epoch 2/3
25000/25000 [==============================] - 2s 75us/step - loss: 0.2345 - acc: 0.9143
Epoch 3/3
25000/25000 [==============================] - 2s 77us/step - loss: 0.1793 - acc: 0.9337
[[0.71075773]
 [0.11593208]
 [0.14267255]
 [0.77756345]]
